package Unidad2;

import Unidad3.dlgFijo;
import Unidad3.dlgGaussSeidel;
import Unidad3.dlgJacobi;

 
public class frmPrincipal extends javax.swing.JFrame {

   
    public frmPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        mnbPestanas = new javax.swing.JMenuBar();
        mnOpciones = new javax.swing.JMenu();
        smnuPuntoFijo = new javax.swing.JMenuItem();
        smnuNewton = new javax.swing.JMenuItem();
        smnuSecante = new javax.swing.JMenuItem();
        smnuBiseccion = new javax.swing.JMenuItem();
        mnOpcionesEcu = new javax.swing.JMenu();
        jmiJacobbi = new javax.swing.JMenuItem();
        jmiPuntoFijo = new javax.swing.JMenuItem();
        Gauss = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        mnOpciones.setText("Métodos No Lineales");

        smnuPuntoFijo.setText("Punto Fijo");
        smnuPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuPuntoFijoActionPerformed(evt);
            }
        });
        mnOpciones.add(smnuPuntoFijo);

        smnuNewton.setText("Newton");
        smnuNewton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuNewtonActionPerformed(evt);
            }
        });
        mnOpciones.add(smnuNewton);

        smnuSecante.setText("Secante");
        smnuSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuSecanteActionPerformed(evt);
            }
        });
        mnOpciones.add(smnuSecante);

        smnuBiseccion.setText("Bisección");
        smnuBiseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smnuBiseccionActionPerformed(evt);
            }
        });
        mnOpciones.add(smnuBiseccion);

        mnbPestanas.add(mnOpciones);

        mnOpcionesEcu.setText("Sistemas de Ecuaciones");

        jmiJacobbi.setText("Jacobbi");
        jmiJacobbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiJacobbiActionPerformed(evt);
            }
        });
        mnOpcionesEcu.add(jmiJacobbi);

        jmiPuntoFijo.setText("Punto Fijo");
        jmiPuntoFijo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiPuntoFijoActionPerformed(evt);
            }
        });
        mnOpcionesEcu.add(jmiPuntoFijo);

        Gauss.setText("Gauss-Seidel");
        Gauss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GaussActionPerformed(evt);
            }
        });
        mnOpcionesEcu.add(Gauss);

        mnbPestanas.add(mnOpcionesEcu);

        setJMenuBar(mnbPestanas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(317, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(243, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void smnuBiseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuBiseccionActionPerformed

        dlgBiseccion biseccion = new dlgBiseccion(this,true);
        biseccion.setLocationRelativeTo(null);
        biseccion.setVisible(true);
        
    }//GEN-LAST:event_smnuBiseccionActionPerformed

    private void smnuPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuPuntoFijoActionPerformed
        dlgFijo punto = new dlgFijo(this,true);
        punto.setLocationRelativeTo(null);
        punto.setVisible(true);
    }//GEN-LAST:event_smnuPuntoFijoActionPerformed

    private void smnuSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuSecanteActionPerformed
        dlgSecante secante = new dlgSecante(this,true);
        secante.setLocationRelativeTo(null);
        secante.setVisible(true);
    }//GEN-LAST:event_smnuSecanteActionPerformed

    private void smnuNewtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smnuNewtonActionPerformed
        dlgNewton newton = new dlgNewton(this,true);
        newton.setLocationRelativeTo(null);
        newton.setVisible(true);
    }//GEN-LAST:event_smnuNewtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmiJacobbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiJacobbiActionPerformed
        dlgJacobi x = new dlgJacobi();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
    }//GEN-LAST:event_jmiJacobbiActionPerformed

    private void jmiPuntoFijoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiPuntoFijoActionPerformed
        dlgFijo y = new dlgFijo(this,true);
        y.setLocationRelativeTo(null);
        y.setVisible(true);
    }//GEN-LAST:event_jmiPuntoFijoActionPerformed

    private void GaussActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GaussActionPerformed
    dlgGaussSeidel y = new dlgGaussSeidel();
        y.setLocationRelativeTo(null);
        y.setVisible(true);
    }//GEN-LAST:event_GaussActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Gauss;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenuItem jmiJacobbi;
    private javax.swing.JMenuItem jmiPuntoFijo;
    private javax.swing.JMenu mnOpciones;
    private javax.swing.JMenu mnOpcionesEcu;
    private javax.swing.JMenuBar mnbPestanas;
    private javax.swing.JMenuItem smnuBiseccion;
    private javax.swing.JMenuItem smnuNewton;
    private javax.swing.JMenuItem smnuPuntoFijo;
    private javax.swing.JMenuItem smnuSecante;
    // End of variables declaration//GEN-END:variables


}
